# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Philcomp
author: Sean Walsh
logo: philcomp.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: philcomp.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - philcomp.bib


# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year
    
# Information about where the book exists on the web
repository:
  url                       : https://github.com/logic-teaching/philcompbook/  # Online location of your book
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)